Import("env")

env.Program("gimli-hash.c")
env.Program("null-gimli-hash.c")
env.Program("null-gimli-aead.c")

env.Program("lith-keygen.c")
env.Program("lith-sign.c")
env.Program("lith-verify.c")
env.Program("null-lith-verify.c")
